stages:

  # スライド生成用のプロンプトを生成する
  generate_prompt:
    matrix:
      theme_keyword: ${theme_keywords}
    cmd: >-
      poetry run python -m src.generate_prompt
      src/meta_prompt.md
      data/interim/prompt_sample_${item.theme_keyword}.md
      --theme_keyword=${item.theme_keyword}
    deps:
    - src/generate_prompt.py
    - src/meta_prompt.md
    outs:
    - data/interim/prompt_sample_${item.theme_keyword}.md

  # スライドを生成する
  generate_scenario:
    matrix:
      id: ${ids}
    cmd: >-
      poetry run python -m src.generate_scenario
      src/prompt.md
      data/interim/scenario-${item.id}.md
      --temperature=${temperature}
    deps:
    - src/generate_scenario.py
    - src/prompt.md
    outs:
    - data/interim/scenario-${item.id}.md

  # Marp Markdown から PDF に変換する
  convert_markdown_to_pdf:
    matrix:
      id: ${ids}
    cmd: >-
      mkdir -p build ; rm -f build/* ;
      cp src/style.css build/ ;
      cp data/interim/scenario-${item.id}.md build/temp.md ;
      docker run --rm -v ./build/:/home/marp/app marp-cli-ja marp
      temp.md -o temp.pdf --pdf --theme style.css;
      cp build/temp.pdf
      data/interim/scenario-${item.id}.pdf
    deps:
    - src/style.css
    - data/interim/scenario-${item.id}.md
    outs:
    - data/interim/scenario-${item.id}.pdf

  # Marp Markdown から HTML に変換する
  convert_markdown_to_html:
    matrix:
      id: ${ids}
    cmd: >-
      mkdir -p build ; rm -f build/* ;
      cp src/style.css build/ ;
      cp data/interim/scenario-${item.id}.md build/temp.md ;
      docker run --rm -v ./build/:/home/marp/app marp-cli-ja marp
      temp.md -o temp.html --html --theme style.css;
      cp build/temp.html
      data/interim/scenario-${item.id}.html
    deps:
    - src/style.css
    - data/interim/scenario-${item.id}.md
    outs:
    - data/interim/scenario-${item.id}.html

  # Marp Markdown から編集可能な PPTX に変換する
  convert_markdown_to_pptx:
    matrix:
      id: ${ids}
    cmd: >-
      poetry run python -m src.md_to_pptx
      data/interim/scenario-${item.id}.md
      data/processed/scenario-${item.id}.pptx
    deps:
    - src/md_to_pptx.py
    - data/interim/scenario-${item.id}.md
    outs:
    - data/processed/scenario-${item.id}.pptx

  # PPTX から PDF に変換する(LibreOfficが必要)
  convert_pptx_to_pdf:
    matrix:
      id: ${ids}
    cmd: >-
      libreoffice --headless --convert-to pdf
      data/processed/scenario-${item.id}.pptx
      --outdir data/processed/
    deps:
    - data/processed/scenario-${item.id}.pptx
    outs:
    - data/processed/scenario-${item.id}.pdf

  # Marp Markdown から画像ファイルを生成する
  generate_images:
    matrix:
      id: ${ids}
    cmd: >-
      poetry run python -m src.generate_images
      data/interim/scenario-${item.id}.md
      data/interim/scenario-${item.id}_with_image.md
      data/interim/images-${item.id}/
      --temperature=${temperature}
      --enable_dummy=${enable_dummy}
    deps:
    - src/generate_images.py
    - data/interim/scenario-${item.id}.md
    outs:
    - data/interim/scenario-${item.id}_with_image.md
    - data/interim/images-${item.id}/

  # Marp Markdown と生成された画像から PDF を作成する
  convert_markdown_to_pdf_with_image:
    matrix:
      id: ${ids}
    cmd: >-
      mkdir -p build ; rm -fr build/* ;
      cp src/style.css build/ ;
      cp data/interim/scenario-${item.id}_with_image.md build/temp.md ;
      cp -r data/interim/images-${item.id} build/ ;
      docker run --rm -v ./build/:/home/marp/app marp-cli-ja marp
      temp.md -o temp.pdf --pdf --theme style.css
      --allow-local-files ;
      cp build/temp.pdf
      data/interim/scenario-${item.id}_with_image.pdf
    deps:
    - src/style.css
    - data/interim/scenario-${item.id}_with_image.md
    - data/interim/images-${item.id}/
    outs:
    - data/interim/scenario-${item.id}_with_image.pdf

  # Marp Markdown と生成された画像から HTML を作成する
  convert_markdown_to_html_with_image:
    matrix:
      id: ${ids}
    cmd: >-
      mkdir -p build ; rm -fr build/* ;
      cp src/style.css build/ ;
      cp data/interim/scenario-${item.id}_with_image.md build/temp.md ;
      cp -r data/interim/images-${item.id} build/ ;
      docker run --rm -v ./build/:/home/marp/app marp-cli-ja marp
      temp.md -o temp.html --html --theme style.css
      --allow-local-files ;
      cp build/temp.html
      data/interim/scenario-${item.id}_with_image.html
    deps:
    - src/style.css
    - data/interim/scenario-${item.id}_with_image.md
    - data/interim/images-${item.id}/
    outs:
    - data/interim/scenario-${item.id}_with_image.html

  # Marp Markdown から編集可能な PPTX に変換する
  convert_markdown_to_pptx_with_image:
    matrix:
      id: ${ids}
    cmd: >-
      poetry run python -m src.md_to_pptx
      data/interim/scenario-${item.id}_with_image.md
      data/processed/scenario-${item.id}_with_image.pptx
    deps:
    - src/md_to_pptx.py
    - data/interim/scenario-${item.id}_with_image.md
    - data/interim/images-${item.id}/
    outs:
    - data/processed/scenario-${item.id}_with_image.pptx

  # PPTX から PDF に変換する(LibreOfficが必要)
  convert_pptx_to_pdf_with_image:
    matrix:
      id: ${ids}
    cmd: >-
      libreoffice --headless --convert-to pdf
      data/processed/scenario-${item.id}_with_image.pptx
      --outdir data/processed/
    deps:
    - data/processed/scenario-${item.id}_with_image.pptx
    outs:
    - data/processed/scenario-${item.id}_with_image.pdf

