ids:
  - 0
  # - 1
  # - 2
  # - 3
  # - 4
  # - 5
temperature: 0.8
theme_keywords:
  - 時系列解析
  - 線形ガウス状態空間モデル
  - 異常検知
  - 推薦モデル
  - 強化学習
  - 最適化問題
  - ベイズ統計による検定
  - 統計的仮説検定
  - 反実仮想機械学習
  - テキスト埋め込みモデルを利用したベクトル検索
